import './styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/app/component/nav/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'School Management System',
  description: 'Generated by Nasib'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="z-50 sticky top-0">
        <Header />
        </div>
      <div className="flex min-h-screen flex-col items-center justify-between  mx-auto px-12 2xl:max-w-7xl max-w-6xl w-screen pt-4 pb-1 bg-gray-100 z-10">
      {children}
    </div>
        </body>
    </html>
  )
}
